import './blocks/whats-included/index.js';
import './blocks/details-compatibility/index.js';
import './blocks/single-meta/index.js';
import './blocks/support/index.js';
import './blocks/version/index.js';
import './blocks/documentation/index.js';
import './blocks/extension/index.js';
import './blocks/call-to-action/index.js';
import './blocks/product-description/index.js';
